name: currency_converter_test
description: Currency converter test.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.3

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.4

  #data base
  floor: ^1.4.2

  #make request to api
  dio: ^5.3.2

  #provider:
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6


flutter:
  uses-material-design: true